language: android
dist: trusty
jdk: oraclejdk8

env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3

android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-ANDROID_API_LEVEL

before_install:
  - cd FoodtruckClient
  - yes | sdkmanager "platforms;android-28"

before_script:
  - chmod +x gradlew