language: android
dist: xenial
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-28.0.3

before_install:
  - cd FoodtruckClient
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"