language: android
dist: xenial
jdk: oraclejdk8

android:
  components:
    - build-tools-28.0.3
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  - cd FoodtruckClient
  - pwd
  - chmod +x gradlew